name: PHPUnit

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP with fail-fast
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
              env:
                  fail-fast: true

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Install PKL
              run: ./phpkl install

            - name: PHPCS Fixer
              run: composer run-script cs

            - name: PHPStan
              run: composer run-script stan

            - name: Run test suite
              run: composer run-script test
